//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonsApp.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FluentValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluentValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonsApp.Application.Resources.FluentValidationMessages", typeof(FluentValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Contain {1} Symbols.
        /// </summary>
        public static string ExactLength {
            get {
                return ResourceManager.GetString("ExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mustn&apos;t Contain More Than {1} Symbols.
        /// </summary>
        public static string LongerThanMaxLength {
            get {
                return ResourceManager.GetString("LongerThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Must Be Older Than 18.
        /// </summary>
        public static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Be Greater Then {1} .
        /// </summary>
        public static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Contain Georgian Or Latin Symbols.
        /// </summary>
        public static string MustContainGeorgianAndLatin {
            get {
                return ResourceManager.GetString("MustContainGeorgianAndLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Contain Only Digits.
        /// </summary>
        public static string MustContainOnlyDigits {
            get {
                return ResourceManager.GetString("MustContainOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Exists.
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must Contain More Then {1} Symbols.
        /// </summary>
        public static string ShorterThanMinLength {
            get {
                return ResourceManager.GetString("ShorterThanMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
